schema_version = "1.0.0"

id = "add_subdivided_cube"
version = "1.0.0"

name = "Add Subdivided Cube(创建立方体体时设置细分)"
tagline = "Add Subdivided Cube(创建立方体体时设置细分)"

maintainer = "magicianlib <magicianlib@outlook.com>"

# Supported types: "add-on", "theme"
type = "add-on"

tags = ["Add Curve"]

blender_version_min = "4.2.0"

# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
    "SPDX:GPL-2.0-or-later",
]